export function generateRandomUsername() {
	const randomAdjective = adjectives[Math.floor(Math.random() * adjectives.length)];
	const randomAnimal = animals[Math.floor(Math.random() * animals.length)];
	const randomNumber = Math.floor(Math.random() * 1000);
	return `${randomAdjective} ${randomAnimal} ${randomNumber}`;
}

const adjectives = [
	'adorable',
	'beautiful',
	'clean',
	'drab',
	'elegant',
	'fancy',
	'glamorous',
	'handsome',
	'long',
	'magnificent',
	'old-fashioned',
	'plain',
	'quaint',
	'sparkling',
	'ugliest',
	'unsightly',
	'angry',
	'bewildered',
	'clumsy',
	'defeated',
	'embarrassed',
	'fierce',
	'grumpy',
	'helpless',
	'itchy',
	'jealous',
	'lazy',
	'mysterious',
	'nervous',
	'obnoxious',
	'panicky',
	'repulsive',
	'scary',
	'thoughtless',
	'uptight',
	'worried',
];
const animals = [
	'alligator',
	'ant',
	'bat',
	'bear',
	'beaver',
	'bird',
	'camel',
	'cat',
	'chicken',
	'cow',
	'crocodile',
	'deer',
	'dog',
	'dolphin',
	'duck',
	'eagle',
	'elephant',
	'fish',
	'fox',
	'frog',
	'goat',
	'gorilla',
	'lion',
	'lizard',
	'monkey',
	'mouse',
	'octopus',
	'panda',
	'pig',
	'rabbit',
	'rhinoceros',
	'sheep',
	'snake',
	'squirrel',
	'tiger',
	'wolf',
];